#!/bin/sh

#   focusmover {west,south,north,east} 
bspc config pointer_follows_monitor false; 
bspc config pointer_follows_focus false; 
dir=$@; 
if ! bspc node -f $dir; then 
    bspc monitor -f $dir; 
fi; 
bspc config pointer_follows_monitor false;
bspc config pointer_follows_focus false
